#################################################################################
##                   _                        _  _____ __  __                  ##
##_________________ | |     ___ __      __ __| ||  ___|\ \/ / _________________##
##_________________ | |    / _ \\ \ /\ / // _` || |_    \  /  _________________##
##_________________ | |___| (_) |\ V  V /| (_| ||  _|   /  \  _________________##
##_________________ |_____|\___/  \_/\_/  \__,_||_|    /_/\_\ _________________##
##                                Configuration                                ##
#################################################################################

language: "de"
## Alle Nachrichten, wenn Spieler den Server betreten oder verlassen.
# Im MiniMessage format: https://docs.advntr.dev/minimessage/index.html.
# Der Placeholder "{0}" ist der Spielername.

## Allgemeine Einstellungen.
basic:

  # Steht vor jeder Befehlsnachricht.
  server-name: "LoudCraft"

  # Custom /help Befehl vom Plugin an/aus
  customhelp: true

## Öfen Einstellungen.
# speed_multiplier: Teilt die Koch-Zeit (höher = schneller)
# particle: Partikel-Effekt beim Upgrade und Schmelzen
requirements:
  1:
    material: IRON_INGOT
    amount: 32
    xp_levels: 0
    speed_multiplier: 2
    particle: SMOKE
  2:
    material: GOLD_INGOT
    amount: 32
    xp_levels: 0
    speed_multiplier: 3
    particle: FLAME
  3:
    material: DIAMOND
    amount: 32
    xp_levels: 0
    speed_multiplier: 4
    particle: CLOUD
  4:
    material: NETHERITE_INGOT
    amount: 20
    xp_levels: 0
    speed_multiplier: 5
    particle: SOUL_FIRE_FLAME
  5:
    material: NETHERITE_INGOT
    amount: 30
    xp_levels: 100
    speed_multiplier: 6
    particle: TOTEM_OF_UNDYING

